language: node_js
node_js:
  - "7"
addons:
    code_climate:
        repo_token: 81ec7b92fcc00779fba3624e3b840f3e4c1f708e
before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search
